name: React Production Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      CI: true
      BUILD_PATH: /home/ubuntu/frontend/_work/pub_cicd_frontend/pub_cicd_frontend/build
    
    steps:
    # 1. Cache Optimization
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
    # 2. Code Setup
    - uses: actions/checkout@v3
    
    # 3. Node.js Setup
    - uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
    
    # 4. Smart Dependency Installation
    - name: Install Dependencies
      run: |
        if [ -d node_modules ]; then
          npm ci --prefer-offline --no-audit --silent
        else
          npm ci --no-audit --silent
        fi
    
    # 5. Fast Production Build
    - name: Build Project
      run: npm run build --if-present
    
    # 6. Atomic Deployment
    - name: Deploy to Production
      run: |
        TEMP_DIR=$(mktemp -d)
        cp -r build/* $TEMP_DIR/
        sudo rsync -a --delete $TEMP_DIR/ ${{ env.BUILD_PATH }}/
        sudo chown -R www-data:www-data ${{ env.BUILD_PATH }}
        sudo find ${{ env.BUILD_PATH }} -type d -exec chmod 755 {} \;
        sudo find ${{ env.BUILD_PATH }} -type f -exec chmod 644 {} \;
        sudo systemctl reload nginx
        rm -rf $TEMP_DIR